In [2]:
import numpy as np

In [5]:
x = np.array([1,2,4])
y = np.array([10,11,12])
print(x*y)

[10 22 48]


In [6]:
print("Value : {}, Type : {}".format(x,type(x)))

Value : [1 2 4], Type : <class 'numpy.ndarray'>


In [10]:
a = np.array(
    [
    [1,2,4],
    [2,3,4]
    ]
)

In [11]:
a

array([[1, 2, 4],
       [2, 3, 4]])

In [12]:
np.ones

<function numpy.ones(shape, dtype=None, order='C')>

In [22]:
np.ones(x)

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [14]:
np.ones([2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.diag([2,3,5,6])

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 6]])

In [29]:
x = np.arange(start=0, stop=500, step=20)
x

array([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180, 200, 220, 240,
       260, 280, 300, 320, 340, 360, 380, 400, 420, 440, 460, 480])

In [31]:
x[-10:-4:2]

array([300, 340, 380])

In [58]:
x=np.random.random([2,3])

In [60]:
x

array([[0.64597411, 0.00783109, 0.69791031],
       [0.37586257, 0.0691751 , 0.99605734]])

In [62]:
x.T

array([[0.64597411, 0.37586257],
       [0.00783109, 0.0691751 ],
       [0.69791031, 0.99605734]])